sudo: false
language: ruby
rvm:
  - 2.2.5

install:
  - gem install jekyll

script:
  - make build

deploy:
  - provider: s3
    on:
      branch: preview
    local_dir: _site
    bucket: preview.emacsair.me
    region: eu-central-1
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
  - provider: s3
    on:
      branch: master
    local_dir: _site
    bucket: emacsair.me
    region: eu-central-1
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
